spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/\${POSTGRES_DB}
    username: \${POSTGRES_USER}
    password: \${POSTGRES_PASSWORD}
app:
  potluck-sheet:
    version: ${project.version}
    build-year: ${buildYear}
    dietary-restrictions:
      - name: Vegan
        color: "#d9f7be"  # Light green
      - name: Vegetarisch
        color: "#fff2cc"  # Light yellow
      - name: Laktosefrei
        color: "#cce5ff"  # Light blue
      - name: Glutenfrei
        color: "#e6ccb3"  # Light brown
      - name: Koscher
        color: "#b3d9ff"  # Light blue
      - name: Halal
        color: "#ffd699"  # Light orange
      - name: Diabetes
        color: "#ffb3b3"  # Light red
      - name: Weizen-Allergy
        color: "#fff275"  # Light yellow
      - name: Nussallergie
        color: "#e066ff"  # Light purple
      - name: Ei-Allergie
        color: "#ffc2e0"  # Light pink
      - name: Soja-Allergie
        color: "#d9d9d9"  # Light gray
    tables:
      - name: Essen
        description: Wir möchten ein kaltes Buffet machen, Waffeln oder Ähnliches sind aber auch okay. Ein volles Drei Gänge Menu möchten wir nicht servieren, da ja das Treffen und nicht das Essen im Vordergrund stehen soll.
      - name: Getränke
        description: Jegliche Getränke sind Willkommen, bitte aber keinen harten Alkohol, wenn ihr gerne mit einem Glas Schnaps nach dem Treffen auf das Wiedersehen anstoßen möchtet könnt ihr das gerne tun.
